Entity/Competition.php
<?php

namespace ATM\CompetitionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use ATM\CompetitionBundle\Helpers\Canonicalizer;
use DateTime;

/**
 * @ORM\Entity
 * @ORM\Table(name="atm_competition")
 */
class Competition
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;

    /**
     * @ORM\Column(name="canonical", type="string", length=255, nullable=false)
     */
    private $canonical;

    /**
     * @ORM\Column(name="creation_date", type="datetime", nullable=false)
     */
    private $creation_date;

    /**
     * @ORM\Column(name="init_date", type="datetime", nullable=false)
     */
    private $init_date;

    /**
     * @ORM\Column(name="end_date", type="datetime", nullable=false)
     */
    private $end_date;

    /**
     * @ORM\Column(name="register_init_date", type="datetime", nullable=false)
     */
    private $register_init_date;

    /**
     * @ORM\Column(name="register_end_date", type="datetime", nullable=false)
     */
    private $register_end_date;

    /**
     * @ORM\Column(name="rules", type="text", nullable=false)
     */
    private $rules;

    /**
     * @ORM\Column(name="prices", type="text", nullable=false)
     */
    private $prices;

    /**
     * @ORM\Column(name="folder",  type="string", length=255, nullable=false)
     */
    private $folder;

    /**
     * @ORM\Column(name="image", type="text", nullable=false)
     */
    private $image;

    /**
     * @ORM\Column(name="image_mobile", type="text", nullable=true)
     */
    private $image_mobile;

    /**
     * @ORM\Column(name="image_middle", type="text", nullable=true)
     */
    private $image_middle;

    /**
     * @ORM\OneToMany(targetEntity="Contestant", mappedBy="competition", cascade={"remove"})
     */
    protected $contestants;

    public function __construct()
    {
        $this->creation_date = new DateTime();
        $this->contestants = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
        $this->canonical = Canonicalizer::canonicalize($name);
    }

    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;
    }

    public function getInitDate()
    {
        return $this->init_date;
    }

    public function setInitDate($init_date)
    {
        $this->init_date = $init_date;
    }

    public function getEndDate()
    {
        return $this->end_date;
    }

    public function setEndDate($end_date)
    {
        $this->end_date = $end_date;
    }

    public function getRules()
    {
        return $this->rules;
    }

    public function setRules($rules)
    {
        $this->rules = $rules;
    }

    public function getPrices()
    {
        return $this->prices;
    }

    public function setPrices($prices)
    {
        $this->prices = $prices;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImageMobile()
    {
        return $this->image_mobile;
    }

    public function setImageMobile($image_mobile)
    {
        $this->image_mobile = $image_mobile;
    }

    public function getContestants(){
        return $this->contestants;
    }

    public function addContestant($contestant){
        $this->contestants->add($contestant);
    }

    public function removeContestant($contestant){
        $this->contestants->removeElement($contestant);
    }

    public function getFolder()
    {
        return $this->folder;
    }

    public function setFolder($folder)
    {
        $this->folder = $folder;
    }

    public function getCanonical()
    {
        return $this->canonical;
    }

    public function setCanonical($canonical)
    {
        $this->canonical = $canonical;
    }

    public function getRegisterInitDate()
    {
        return $this->register_init_date;
    }

    public function setRegisterInitDate($register_init_date)
    {
        $this->register_init_date = $register_init_date;
    }

    public function getRegisterEndDate()
    {
        return $this->register_end_date;
    }

    public function setRegisterEndDate($register_end_date)
    {
        $this->register_end_date = $register_end_date;
    }

    public function getImageMiddle()
    {
        return $this->image_middle;
    }

    public function setImageMiddle($image_middle)
    {
        $this->image_middle = $image_middle;
    }
}

Controller/FrontendController.php
<?php

namespace ATM\CompetitionBundle\Controller;

use ATM\CompetitionBundle\Document\CompetitionIpRequest;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use ATM\CompetitionBundle\Entity\AnonymousUser;
use ATM\CompetitionBundle\Entity\Image;
use ATM\CompetitionBundle\Entity\Contestant;
use ATM\CompetitionBundle\Document\CompetitionVote;
use ATM\CompetitionBundle\Services\SearchIpRequests;
use ATM\CompetitionBundle\Services\ImageManager;
use ATM\CompetitionBundle\Services\SearchVotes;
use ATM\CompetitionBundle\Services\SearchCompetition;
use ATM\CompetitionBundle\Services\SearchContestants;
use ATM\CompetitionBundle\Event\NewContestant;
use \DateTime;

class FrontendController extends Controller
{
    /**
     * @Route("/competition/{canonical}/{competitionId}/{page}", name="atm_competition_landing", defaults={"page":1})
     */
    public function landingAction($canonical,$competitionId, $page)
    {
        $em = $this->getDoctrine()->getManager();
        $competition = $em->getRepository('ATMCompetitionBundle:Competition')->findOneById($competitionId);

        if($competition){
            $config = $this->getParameter('atm_competition_config');

            return $this->render('ATMCompetitionBundle:Frontend:'.$canonical.'.html.twig',array(
                'competition' => $competition,
                'contestant_role' => $config['contestant_role'],
                'page' => $page
            ));
        }else{
            return $this->render('ATMCompetitionBundle:Frontend:competition_not_found.html.twig');
        }
    }

    /**
     * @Route("/contestant/join/competition/{competitionId}", name="atm_competition_contestant_join")
     */
    public function competitionContestantJoinAction($competitionId){
        $em = $this->getDoctrine()->getManager();
        $user = $this->get('security.token_storage')->getToken()->getUser();
        $competition = $em->getRepository('ATMCompetitionBundle:Competition')->findOneById($competitionId);

        $contestant = $em->getRepository('ATMCompetitionBundle:Contestant')->findOneBy(array(
            'competition' =>$competitionId,
            'user' => $user->getId()
        ));

        if(!is_null($contestant)){

            $this->get('session')->getFlashBag()->set('atm_competition_not_allowed','You are already a contestant in this competition');

            return new RedirectResponse($this->get('router')->generate('atm_competition_landing',array(
                'competitionId' => $competitionId,
                'canonical' => $competition->getCanonical()
            )));
        }
        $config = $this->getParameter('atm_competition_config');


        if($this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY') && in_array($config['contestant_role'],$user->getRoles())){
            $request = $this->get('request_stack')->getCurrentRequest();

            if($request->getMethod() == 'POST'){
                $contestant = new Contestant();
                $contestant->setUser($user);
                $contestant->setName($user->getUsername());
                $contestant->setEmail($user->getEmail());
                $contestant->setCompetition($competition);

                if(!is_null($config['media_entity']['namespace'])){
                    $mediaId = $request->get('user_media');
                    $media = $em->getRepository($config['media_entity']['namespace'])->findOneById($mediaId);
                    $contestant->setMedia($media);
                }

                $em->persist($contestant);

                $userFolder = $this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder().'/'.$user->getUsernameCanonical();
                if(!is_dir($this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder())){
                    mkdir($this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder());
                }

                if(!is_dir($userFolder)){
                    mkdir($userFolder);
                }

                $mainImageFile = $request->files->get('main_image');
                $mainImageFilename= $this->get(ImageManager::class)->cropImage($mainImageFile,$userFolder,false,true);

                $mainImage = new Image();
                $mainImage->setPath($config['media_folder'].'/'.$competition->getFolder().'/'.$user->getUsernameCanonical().'/'.$mainImageFilename);
                $mainImage->setIsMain(true);
                $mainImage->setContestant($contestant);
                $em->persist($mainImage);

                $images = $request->files->get('images');
                if($images){
                    foreach($images as $img){
                        $filename = md5(uniqid()).'.'.$img->guessExtension();
                        $img->move($userFolder,$filename);
                        $this->get(ImageManager::class)->watermarkImage(
                            $this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder().'/'.$user->getUsernameCanonical().'/'.$filename,
                            $this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder().'/'.$user->getUsernameCanonical().'/'.$filename
                        );

                        $image = new Image();
                        $image->setPath($config['media_folder'].'/'.$competition->getFolder().'/'.$user->getUsernameCanonical().'/'.$filename);
                        $image->setContestant($contestant);
                        $em->persist($image);
                    }
                }

                $em->flush();

                $event = new NewContestant($contestant,$competition);
                $this->get('event_dispatcher')->dispatch(NewContestant::NAME, $event);

                return new RedirectResponse($this->get('router')->generate('atm_competition_landing',array(
                    'competitionId' => $competitionId,
                    'canonical' => $competition->getCanonical()
                )));
            }

            $params = array('ids' => array($competitionId));

            $competitions = $this->get(SearchCompetition::class)->search($params);

            return $this->render('ATMCompetitionBundle:Frontend:upload_images.html.twig',array(
                'competitionId' => $competitionId,
                'competition' => $competitions['results'][0],
                'media_namespace' => $config['media_entity']['namespace']
            ));
        }else{
            $this->get('session')->getFlashBag()->set('atm_competition_not_allowed',$config['messages']['not_allowed']);
            return new RedirectResponse($this->get('router')->generate('atm_competition_landing',array('competitionId'=> $competitionId,'canonical'=>$competition->getCanonical())));
        }
    }


    public function searchContestantsAction($params){

        $config = $this->getParameter('atm_competition_config');
        $contestants = $this->get(SearchContestants::class)->search($params);

        return $this->render('ATMCompetitionBundle:Frontend:search_results.html.twig',array(
            'contestants' => $contestants['results'],
            'pagination' => $contestants['pagination'],
            'competition_id' => $params['competition'],
            'contestant_role' => $config['contestant_role'],
        ));
    }

    /**
     * @Route("/contestant/details/{contestantId}", name="atm_competition_contestant_details")
     */
    public function contestantDetailsAction($contestantId){
        $params = array(
            'ids' => array($contestantId)
        );
        $contestant = $this->get(SearchContestants::class)->search($params);

        return $this->render('ATMCompetitionBundle:Frontend:contestant_details.html.twig',array(
            'contestant' => $contestant['results'][0]
        ));
    }

    /**
     * @Route("/check/email/{email}", name="atm_competition_check_email", options={"expose"=true})
     */
    public function checkEmailAction($email){
        $curl = curl_init();
        curl_setopt_array($curl, array(
            CURLOPT_RETURNTRANSFER => 1,
            CURLOPT_URL => 'https://disposable.debounce.io/?email='.$email
        ));

        $result = json_decode(curl_exec($curl),true);
        $validEmail = $result['disposable'] == 'false' ? false : true;

        if($validEmail === false){
            $this->get('session')->set('atm_competition_email_ok',$email);
        }


        return new Response($validEmail === true ? 'ko' : 'ok');
    }

    /**
     * @Route("/anonymous/user/send/email/{email}/{contestantId}", name="atm_competition_anonymous_user_send_mail", options={"expose"=true})
     */
    public function anonymousUserSendVoteLinkAction($email,$contestantId){
        $config = $this->getParameter('atm_competition_config');
        $contestant = $this->get(SearchContestants::class)->search(array('email'=>$email,'ids'=> $contestantId));
        $competition = $contestant['results'][0]['competition'];

        $request = $this->get('request_stack')->getCurrentRequest();
        $ip = $request->getClientIp();
        $currentDate = new DateTime();
        $currentDate->setTime('0','0','0');
        $numberIpRequest = $this->get(SearchIpRequests::class)->search($ip,$currentDate);

        if($numberIpRequest > 0){
            $this->get('session')->getFlashBag()->set('atm_competition_already_voted',$config['messages']['already_voted']);
            return new RedirectResponse($this->get('router')->generate('atm_competition_landing',array(
                'canonical' => $competition['canonical'],
                'competitionId' => $competition['id']
            )));
        }else{

Resources/views/Frontend/competition_not_found.html.twig
<html><body>
    <p>THE COMPETITION THAT YOU REQUESTED DOESN'T EXIST</p>
</body></html>

Resources/views/Frontend/contestant_details.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}

{% block atm_competition_menu %}{% endblock atm_competition_menu %}

{% block atm_competition_content %}
    <div class="wide contestant_details">
        <div class="quarter">
            {% for image in contestant.images %}
                {% if image.isMain %}
                    <img src="{{ asset(image.path) }}">
                {% endif %}
            {% endfor %}
            <span>{{ contestant.name | title }}</span>
            {% if app.user %}
                <a class="but red vote" href="{{ path('atm_competition_user_vote',{ 'contestantId':contestant.id }) }}">Vote</a>
            {% else %}
                <a class="but red vote btnPopVote" data-contestant-id="{{ contestant.id }}">Vote</a>
            {% endif %}
        </div>
        <div class="threequarter">
            {% for image in contestant.images %}
                {% if not image.isMain %}
                    <img class="quarter" src="{{ asset(image.path) }}">
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

Resources/views/Frontend/default_template.html.twig
{% extends 'MMFrontendBundle:www.%sitename%:base.html.twig' %}

{% block title %}{{ competition.name }} Competition - BikiniFanatics{% endblock title %}
{% block meta_description %}{{ competition.rules | striptags }}{% endblock meta_description %}
{% block meta_keywords %}{{ app.user ? 'members only, member area' : 'Competion, bikini contest' }}{% endblock meta_keywords %}

{% block twitter_metas %}
    <meta property="twitter:url" content="{{ app.request.uri }}">
    <meta property="twitter:title" content="{{ competition.name }} Competition - BikiniFanatics">
    <meta property="twitter:description" content="{{ competition.rules | striptags }}">
    <meta property="twitter:image" content="{{ asset(competition.image) }}">

    <meta property="og:type" content="{{ app.request.uri }}">
    <meta property="og:title" content="{{ competition.name }} Competition - BikiniFanatics">
    <meta property="og:description" content="{{ competition.rules | striptags }}">
    <meta property="og:image" content="{{ asset(competition.image) }}">
{% endblock twitter_metas %}

{% block content %}
    <div class="competition_header{% if not app.user %} competition_header_tour{% endif %}">
        <a class="view_all_competitions" href="{{ path(getRoutePrefix() ~ '_competitions') }}" title="View All Competitions"><i class="fas fa-chevron-left"></i> View All Competitions</a>
        <img class="_detectdevice" data-src-desktop="{{ getCDNResource({'media_path': asset(competition.image)}) }}"
             data-src-mobile="{{ getCDNResource({'media_path': asset(competition.imageMobile)}) }}" alt="{{ competition.name }}" />

        <div class="competition_header_overlay">
            <h1>{{ competition.name | title }}</h1>
            <div class="clear"></div>

            {% if ATMCompIsRegisterPeriod(competition.id)%}
                <h3>
                    <b>Starts on:</b><br>
                    <span>{{ competition.initDate | date('F dS, Y (g:ia e)') }}</span>
                </h3>
            {% elseif ATMCompIsCompetitionActive(competition.id)%}
                <h3>
                    <b>Ends on:</b><br>
                    <span>{{ competition.endDate | date('F dS, Y (g:ia e)') }}</span>
                </h3>
            {% elseif ATMCompIsFinished(competition.id) %}
                <h3>
                    <b>Congrats to the Winners!</b><br>
                    <span>Competition ended</span>
                </h3>
            {% else %}
                <h3>
                    <b>Starts on:</b><br>
                    <span>{{ competition.initDate | date('F dS, Y (g:ia e)') }}</span>
                </h3>
            {% endif %}
            <div class="clear"></div>

            {% if app.user and ATMCompIsRegisterPeriod(competition.id) %}
                {% if contestant_role in app.user.roles %}
                    {% if not ATMCompIsContestant(competition.id,app.user.id) %}
                        <a href="{{ path('atm_competition_contestant_join',{ 'competitionId':competition.id }) }}" class="click_here">Join Competition</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>

        <div class="competition_inner">
            <div class="competition_left_column">
                <div class="competition_prices">
                    <h2 class="block_title"><i class="fas fa-award"></i> Prizes</h2>
                    {{ competition.prices | raw }}
                </div>
                <div class="clear"></div>
            </div>

            <div class="competition_main_block">
                <div class="competition_rules">
                    <h2 class="block_title"><i class="fas fa-info-circle"></i> Rules</h2>
                    {{ competition.rules | raw }}
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>

    <div class="full_width_block competition_full_width_block">
        <h2 class="block_title"><i class="fas fa-user-circle"></i> Contestants
            {% if app.user and  ATMCompIsRegisterPeriod(competition.id) %}
                {% if contestant_role in app.user.roles %}
                    {% if not ATMCompIsContestant(competition.id,app.user.id) %}
                        <a href="{{ path('atm_competition_contestant_join',{ 'competitionId':competition.id }) }}" class="click_here">Join Competition</a>
                    {% endif %}
                {% endif %}
            {% endif %}
        </h2>
        <div class="clear"></div>

        {{ render(controller('ATMCompetitionBundle:Frontend:searchContestants',{
            'params' : {
                'competition': competition.id,
                'order_by_field': 'votes',
                'order_by_direction': 'ASC'
            }
        })) }}
        <div class="clear"></div>

        {% if not app.user %}
            <div class="tour_join">
                Want to help out your favorite model?<br><a class="click_here" href="{{ path('join_site') }}">Join us now and vote every day!</a>
            </div>
        {% endif %}
    </div>
    {# POPUP BIG IMAGE #}
    <div class="modal fade " id="popImage" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog competition_popup competition_popup_img" role="document">
            <div class="modal-content" style="background: none;">
                <a class="close" data-dismiss="modal" aria-label="Close"><i class="fas fa-times-circle"></i></a>
                <img src="{{ asset(competition.image) }}" id="popContestantBigImage">
            </div>
        </div>
    </div>
    {% include 'MMFrontendBundle:www.%sitename%/popup:atm_competition_vote.html.twig' %}

{% endblock content %}
{% block javascripts %}
    {{ parent() }}
    {% if not app.user %}
        <script>
            var contestantId;
            $('.btnPopVote').click(function(){
                var btn = $(this);
                contestantId = btn.attr('data-contestant-id');
                $('#popVote').modal('show');
            });


            $('#btnVote').click(function (e) {
                e.preventDefault();
                var email = $('#txEmail').val();
                if(email != ''){
                    $.ajax({
                        url: Routing.generate('atm_competition_check_email',{ 'email':email }),
                        type: 'post',
                        success: function(data){
                            if(data == 'ko'){
                                $('#error_msg').show();
                                $('#txEmail').addClass('error');
                            }else{
                                location.href = Routing.generate('atm_competition_anonymous_user_send_mail',{ 'contestantId':contestantId,'email':email });
                            }
                        },
                        error: function(data){
                            $('#error_msg').show();
                            $('#txEmail').addClass('error');
                        }
                    });
                }else{
                    $('#error_msg').show();
                    $('#txEmail').addClass('error');
                }
            });
        </script>
    {% endif %}
    <script>
        $('.btnPopImage').click(function(){
            var btn = $(this);
            var bigImage = btn.attr('data-big-image');
            $('#popContestantBigImage').attr('src',bigImage);
            $('#popImage').modal('show');
        });
        $('#popImage').on('hidden.bs.modal', function (e) {
            $('#popContestantBigImage').attr('src','');
        })
    </script>
{% endblock javascripts %}

Resources/views/Frontend/search_results.html.twig
<div class="contestants">
    {% for contestant in contestants %}
        {% include 'ATMCompetitionBundle:Frontend:item/contestant.html.twig' with { 'contestant':contestant, 'competition_id':competition_id, 'position':loop.index } %}
    {% endfor %}
</div>

{% if pagination is not null %}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endif %}

Resources/views/Frontend/upload_images.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}

{% block atm_competition_menu %}{% endblock atm_competition_menu %}

{% block atm_competition_content %}
    <form action="{{ path('atm_competition_contestant_join',{ 'competitionId':competitionId }) }}" method="post" enctype="multipart/form-data" id="frmUploadImages" class="uploadImages">
        <h1>Join Competition: {{ competition.name | title }}</h1>
        <div class="half mainImageContainer">
            <h1>Main Image</h1>
            <img src="{{ asset('bundles/atmcompetition/images/image-placeholder.png') }}" id="imgMainPreview">
            <input type="file" name="main_image" id="flMainImage">
            {% if media_namespace is not null %}
                {% set media = ATMCompGetLastUserMedia(3,app.user.id) %}
                <fieldset style="margin-top:20px;">
                    <legend>
                        This images belongs to:
                        {% if media|length > 0 %}
                            <div class="selectC">
                                <select name="user_media" required>
                                    <option value=""></option>
                                    {% for item in media %}
                                        <option value="{{ item.id }}">{{ item.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                    </legend>
                </fieldset>
            {% endif %}
        </div>
        <div class="half">
            <h1>Images <a class="but blue btnAddImage" title="Add Image"  style="float:right"><i class="fa fa-plus-circle"></i></a></h1>
            <div class="imagesContainer">
                <div class="clear"></div>
            </div>
        </div>
        <div class="images_uploader" style="float: left;width: 100%;">
            <a class="but blue btnAddImage" title="Add Image" style="float:right"><i class="fa fa-plus-circle"></i></a>
            <input type="submit" class="but blue" name="Upload">
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </form>
    <div class="upload_image" style="display: none">
        <a onclick="$(this).parent().remove()"><i class="fa fa-times-rectangle"></i></a>
        <img src="{{ asset('bundles/atmcompetition/images/image-placeholder.png') }}" class="previewImage">
        <input type="file" name="images[]" class="flImage">
    </div>
{% endblock atm_competition_content %}

{% block atm_competition_javascripts %}
    <script>
        $('#flMainImage').on('change', function() {
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                $('#imgMainPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });

        $('.btnAddImage').click(function(){
            var clone = $('.upload_image').clone();
            clone.removeClass('upload_image').addClass('new_image').show();
            $('.imagesContainer').append(clone);
        });

        $('.imagesContainer').on('change','.flImage',function(){
            var currentInput = $(this);
            var preview = currentInput.siblings('.previewImage');
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                preview.attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });
    </script>
{% endblock atm_competition_javascripts %}