Entity/Competition.php
<?php

namespace ATM\CompetitionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use ATM\CompetitionBundle\Helpers\Canonicalizer;
use DateTime;

/**
 * @ORM\Entity
 * @ORM\Table(name="atm_competition")
 */
class Competition
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name;

    /**
     * @ORM\Column(name="canonical", type="string", length=255, nullable=false)
     */
    private $canonical;

    /**
     * @ORM\Column(name="creation_date", type="datetime", nullable=false)
     */
    private $creation_date;

    /**
     * @ORM\Column(name="init_date", type="datetime", nullable=false)
     */
    private $init_date;

    /**
     * @ORM\Column(name="end_date", type="datetime", nullable=false)
     */
    private $end_date;

    /**
     * @ORM\Column(name="register_init_date", type="datetime", nullable=false)
     */
    private $register_init_date;

    /**
     * @ORM\Column(name="register_end_date", type="datetime", nullable=false)
     */
    private $register_end_date;

    /**
     * @ORM\Column(name="rules", type="text", nullable=false)
     */
    private $rules;

    /**
     * @ORM\Column(name="prices", type="text", nullable=false)
     */
    private $prices;

    /**
     * @ORM\Column(name="folder",  type="string", length=255, nullable=false)
     */
    private $folder;

    /**
     * @ORM\Column(name="image", type="text", nullable=false)
     */
    private $image;

    /**
     * @ORM\Column(name="image_mobile", type="text", nullable=true)
     */
    private $image_mobile;

    /**
     * @ORM\Column(name="image_middle", type="text", nullable=true)
     */
    private $image_middle;

    /**
     * @ORM\OneToMany(targetEntity="Contestant", mappedBy="competition", cascade={"remove"})
     */
    protected $contestants;

    public function __construct()
    {
        $this->creation_date = new DateTime();
        $this->contestants = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setName($name)
    {
        $this->name = $name;
        $this->canonical = Canonicalizer::canonicalize($name);
    }

    public function getCreationDate()
    {
        return $this->creation_date;
    }

    public function setCreationDate($creation_date)
    {
        $this->creation_date = $creation_date;
    }

    public function getInitDate()
    {
        return $this->init_date;
    }

    public function setInitDate($init_date)
    {
        $this->init_date = $init_date;
    }

    public function getEndDate()
    {
        return $this->end_date;
    }

    public function setEndDate($end_date)
    {
        $this->end_date = $end_date;
    }

    public function getRules()
    {
        return $this->rules;
    }

    public function setRules($rules)
    {
        $this->rules = $rules;
    }

    public function getPrices()
    {
        return $this->prices;
    }

    public function setPrices($prices)
    {
        $this->prices = $prices;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImageMobile()
    {
        return $this->image_mobile;
    }

    public function setImageMobile($image_mobile)
    {
        $this->image_mobile = $image_mobile;
    }

    public function getContestants(){
        return $this->contestants;
    }

    public function addContestant($contestant){
        $this->contestants->add($contestant);
    }

    public function removeContestant($contestant){
        $this->contestants->removeElement($contestant);
    }

    public function getFolder()
    {
        return $this->folder;
    }

    public function setFolder($folder)
    {
        $this->folder = $folder;
    }

    public function getCanonical()
    {
        return $this->canonical;
    }

    public function setCanonical($canonical)
    {
        $this->canonical = $canonical;
    }

    public function getRegisterInitDate()
    {
        return $this->register_init_date;
    }

    public function setRegisterInitDate($register_init_date)
    {
        $this->register_init_date = $register_init_date;
    }

    public function getRegisterEndDate()
    {
        return $this->register_end_date;
    }

    public function setRegisterEndDate($register_end_date)
    {
        $this->register_end_date = $register_end_date;
    }

    public function getImageMiddle()
    {
        return $this->image_middle;
    }

    public function setImageMiddle($image_middle)
    {
        $this->image_middle = $image_middle;
    }
}

Controller/CompetitionController.php
<?php

namespace ATM\CompetitionBundle\Controller;

use ATM\CompetitionBundle\Services\SearchContestants;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use ATM\CompetitionBundle\Entity\Competition;
use ATM\CompetitionBundle\Form\CompetitionType;
use ATM\CompetitionBundle\Services\SearchCompetition;
use ATM\CompetitionBundle\Services\SearchVotes;
use ATM\CompetitionBundle\Services\ImageManager;

class CompetitionController extends Controller
{
    /**
     * @Route("/competition/create", name="atm_competition_create")
     */
    public function createCompetitionAction(){
        $config = $this->getParameter('atm_competition_config');
        $competition = new Competition();

        $form = $this->createForm(CompetitionType::class,$competition);
        $request = $this->get('request_stack')->getCurrentRequest();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $config = $this->getParameter('atm_competition_config');
            if(!is_dir($this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'])){
                mkdir($this->get('kernel')->getRootDir().'/../web/'.$config['media_folder']);
            }

            $competitionFolder = md5(uniqid());
            $pathToFolder = $this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competitionFolder;
            mkdir($pathToFolder);

            $file = $request->files->get('flImage');
            $filename = md5(uniqid()).'.'.$file->guessExtension();
            $file->move($pathToFolder,$filename);
            $competition->setFolder($competitionFolder);
            $competition->setImage($config['media_folder'].'/'.$competitionFolder.'/'.$filename);

            $mobileFile = $request->files->get('flImageMobile');
            $mobileImageFile = md5(uniqid()).'.'.$mobileFile->guessExtension();
            $mobileFile->move($pathToFolder,$mobileImageFile);
            $competition->setImageMobile($config['media_folder'].'/'.$competitionFolder.'/'.$mobileImageFile);

            $middleFile = $request->files->get('flImageMiddle');
            $middleImageFile = md5(uniqid()).'.'.$middleFile->guessExtension();
            $middleFile->move($pathToFolder,$middleImageFile);
            $competition->setImageMiddle($config['media_folder'].'/'.$competitionFolder.'/'.$middleImageFile);

            $registerEndDate = $competition->getRegisterEndDate()->modify('23 hours')->modify('59 minutes')->modify('59 seconds');
            $competition->setRegisterEndDate($registerEndDate);

            $endDate = $competition->getEndDate()->modify('+23 hours')->modify('+59 minutes')->modify('+59 seconds');
            $competition->setEndDate($endDate);

            $defaultTemplate = $this->get('kernel')->getRootDir().'/../vendor/atm/competitionbundle/Resources/views/Frontend/default_template.html.twig';
            $competitionTemplate = $this->get('kernel')->getRootDir().'/Resources/ATMCompetitionBundle/views/Frontend/'.$competition->getCanonical().'.html.twig';
            $twigCode = file_get_contents($defaultTemplate);
            $twigCode = str_replace('%sitename%',$config['site_domain'],$twigCode);
            file_put_contents($competitionTemplate,$twigCode);

            $defaultVoteLink = $this->get('kernel')->getRootDir().'/../vendor/atm/competitionbundle/Resources/views/Mail/default_vote_link.html.twig';
            $competitionVoteLink = $this->get('kernel')->getRootDir().'/Resources/ATMCompetitionBundle/views/Mail/'.$competition->getCanonical().'_vote_link.html.twig';
            $twigCodeLink = file_get_contents($defaultVoteLink);
            $twigCodeLink = str_replace('%sitename%',$config['site_domain'],$twigCodeLink);
            file_put_contents($competitionVoteLink,$twigCodeLink);

            $em = $this->getDoctrine()->getManager();
            $em->persist($competition);
            $em->flush();

            return new RedirectResponse($this->get('router')->generate('atm_competition_list'));
        }

        return $this->render('ATMCompetitionBundle:Competition:create.html.twig',array(
            'form' => $form->createView(),
            'froala_key' => $config['froala_key']
        ));
    }

    /**
     * @Route("/competition/edit/{competitionId}", name="atm_competition_edit")
     */
    public function editCompetitionAction($competitionId){
        $config = $this->getParameter('atm_competition_config');
        $em = $this->getDoctrine()->getManager();
        $competition = $em->getRepository('ATMCompetitionBundle:Competition')->findOneById($competitionId);

        $form = $this->createForm(CompetitionType::class,$competition);
        $request = $this->get('request_stack')->getCurrentRequest();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pathToFolder = $this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder();

            $file = $request->files->get('flImage');
            if(!is_null($file)){

                if(file_exists($this->get('kernel')->getRootDir().'/../web/'.$competition->getImage())){
                    unlink($this->get('kernel')->getRootDir().'/../web/'.$competition->getImage());
                }

                $file = $request->files->get('flImage');
                $extension = $file->guessExtension();
                $filename = md5(uniqid()).'.'.$extension;
                $file->move($pathToFolder,$filename);

                $competition->setImage($config['media_folder'].'/'.$competition->getFolder().'/'.$filename);
            }

            $mobileFile = $request->files->get('flImageMobile');
            if($mobileFile){
                if(!is_null($competition->getImageMobile()) && file_exists($this->get('kernel')->getRootDir().'/../web/'.$competition->getImageMobile())){
                    unlink($this->get('kernel')->getRootDir().'/../web/'.$competition->getImageMobile());
                }
                $mobileImageFile = md5(uniqid()).'.'.$mobileFile->guessExtension();
                $mobileFile->move($pathToFolder,$mobileImageFile);
                $competition->setImageMobile($config['media_folder'].'/'.$competition->getFolder().'/'.$mobileImageFile);
            }

            $middleFile = $request->files->get('flImageMiddle');
            if($middleFile){
                if(!is_null($competition->getImageMiddle()) && file_exists($this->get('kernel')->getRootDir().'/../web/'.$competition->getImageMiddle())){
                    unlink($this->get('kernel')->getRootDir().'/../web/'.$competition->getImageMiddle());
                }
                $middleImageFile = md5(uniqid()).'.'.$middleFile->guessExtension();
                $middleFile->move($pathToFolder,$middleImageFile);
                $competition->setImageMiddle($config['media_folder'].'/'.$competition->getFolder().'/'.$middleImageFile);
            }

            $registerEndDate = $competition->getRegisterEndDate()->modify('23 hours')->modify('59 minutes')->modify('59 seconds');
            $competition->setRegisterEndDate($registerEndDate);

            $endDate = $competition->getEndDate()->modify('+23 hours')->modify('+59 minutes')->modify('+59 seconds');
            $competition->setEndDate($endDate);

            $em->persist($competition);
            $em->flush();

            return new RedirectResponse($this->get('router')->generate('atm_competition_list'));
        }

        return $this->render('ATMCompetitionBundle:Competition:edit.html.twig',array(
            'form' => $form->createView(),
            'competition' => $competition,
            'froala_key' => $config['froala_key']
        ));
    }

    /**
     * @Route("/competition/delete/{competitionId}", name="atm_competition_delete")
     */
    public function deleteCompetitionAction($competitionId){
        $em = $this->getDoctrine()->getManager();
        $config = $this->getParameter('atm_competition_config');

        $competition = $em->getRepository('ATMCompetitionBundle:Competition')->findOneById($competitionId);

        $fileSystem = new Filesystem();
        $fileSystem->remove(array('folder',$this->get('kernel')->getRootDir().'/../web/'.$config['media_folder'].'/'.$competition->getFolder()));

        $em->remove($competition);
        $em->flush();

        $dm = $this->get('doctrine_mongodb')->getManager();
        $votes = $dm->getRepository('ATMCompetitionBundle:CompetitionVote')->findBy(array('competition_id'=> $competitionId));
        $count = 0;
        foreach ($votes as $vote){
            $dm->remove($vote);

            if($count % 500 == 0){
                $dm->flush();
            }
            $count++;
        }
        $dm->flush();

        return new RedirectResponse($this->get('router')->generate('atm_competition_list'));
    }

    /**
     * @Route("/competition/list/{page}", name="atm_competition_list", defaults={"page":1})
     */
    public function competitionListAction($page){

        $params = array(
            'page' => $page,
            'pagination' => true,
            'order_by_field' => 'init_date'
        );

        $competitions = $this->get(SearchCompetition::class)->search($params);

        return $this->render('ATMCompetitionBundle:Competition:list.html.twig',array(
            'competitions' => $competitions['results'],
            'pagination' => $competitions['pagination'],
        ));
    }

    /**
     * @Route("/manage/votes/{competitionId}/{page}", name="atm_competition_manage_votes", defaults={"page":1,"competitionId":null}, options={"expose"=true})
     */
    public function manageVotesAction($competitionId,$page){
        $em = $this->getDoctrine()->getManager();

Resources/views/Competition/anonymous_users.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}

{% block atm_competition_stylesheets %}
    <style>
        .manageVotes table{width:85%;margin-top: 30px;}
        .manageVotes table thead tr th, .manageVotes table tbody tr td{text-align:center;padding:5px;}
    </style>
{% endblock atm_competition_stylesheets %}

{% block atm_competition_content %}
    <h1 class="title">Anonymous Users</h1>
    <div class="manageVotes">
        <div class="filters">
            <div class="selectC">
                <select onchange="location.href=Routing.generate('atm_competition_anonymous_users_list',{ 'competitionId':$(this).val() })">
                    <option>Chose a competition</option>
                    {% for competition in competitions %}
                        <option value="{{ competition.id }}" {{ competitionId == competition.id ? 'selected'}}>{{ competition.name }}</option>
                    {% endfor %}
                </select>
            </div>
            {% if competitionId %}
                <a href="{{ path('atm_competition_export_anonymous_users',{ 'competitionId':competitionId }) }}" target="_blank" style="float: right;font-weight: bold;text-decoration: underline;">Export Anonymous users</a>
            {% endif %}
        </div>
        {% if competitionId is not null %}
            <div class="wide">
                <p style="width: 100%;margin: 20px 0;font-weight: bold;text-align: center;font-size: 20px;">Total users : {{ total }}</p>
                <table>
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for anonymousUser in anonymous_users %}
                        <tr>
                            <td>
                                {{ anonymousUser.email }}
                            </td>
                            <td>
                                {{ anonymousUser.creation_date | date('d-m-Y H:i:s') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            {% if pagination %}
                <div class="navigation">
                    {{ knp_pagination_render(pagination) }}
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock atm_competition_content %}

Resources/views/Competition/create.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}

{% block atm_competition_stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/css/jquery-ui.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/css/jquery-ui.theme.min.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/css/froala_editor.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/css/froala_style.css') }}">
    <style>
        .ui-state-default{width: 100% !important;text-align: center !important;}
        .fr-view {font-family:"Quicksand", sans-serif !important;}
    </style>
{% endblock atm_competition_stylesheets %}

{% block atm_competition_content %}
    <form action="{{ path('atm_competition_create') }}" method="post" id="frmCompetition" enctype="multipart/form-data">
        <h1>New Competition</h1>
        <div class="half">
            <fieldset>
                {{ form_widget(form.name) }}
            </fieldset>
            <fieldset>
                <legend>Register init date</legend>
                {{ form_widget(form.register_init_date) }}
            </fieldset>
            <fieldset>
                <legend>Register end date</legend>
                {{ form_widget(form.register_end_date) }}
            </fieldset>
            <fieldset>
                <legend>Voting starts</legend>
                {{ form_widget(form.init_date) }}
            </fieldset>
            <fieldset>
                <legend>Voting ends</legend>
                {{ form_widget(form.end_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.prices) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.rules) }}
            </fieldset>
        </div>
        <div class="half">
            <fieldset>
                <img src="{{ asset('bundles/atmcompetition/images/image-placeholder.png') }}" id="imgPreview">
                <input type="file" name="flImage" id="flImage">
            </fieldset>
        </div>
        <div class="clear"></div>
        <input type="submit" class="but blue" value="Save">
        {{ form_rest(form) }}
    </form>
{% endblock atm_competition_content %}

{% block atm_competition_javascripts %}
    <script src="{{ asset('bundles/atmcompetition/js/jquery-ui.min.1121.js') }}"></script>
    <script src="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/js/froala_editor.min.js') }}"></script>
    <script src="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/js/plugins/link.min.js') }}"></script>
    <script>
        $( function() {
            var dateFormat = "dd-mm-yy",
                from = $( "#competition_init_date" )
                    .datepicker({
                        dateFormat: dateFormat,
                        defaultDate: "+1w",
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                to = $( "#competition_end_date" ).datepicker({
                    dateFormat: dateFormat,
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    from.datepicker( "option", "maxDate", getDate( this ) );
                }),
                register_from = $( "#competition_register_init_date" )
                    .datepicker({
                        dateFormat: dateFormat,
                        defaultDate: "+1w",
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        register_to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                register_to = $( "#competition_register_end_date" ).datepicker({
                    dateFormat: dateFormat,
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    register_from.datepicker( "option", "maxDate", getDate( this ) );
                });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }

                return date;
            }
        } );

        $('#flImage').on('change', function() {
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                $('#imgPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });

        $('#competition_rules').froalaEditor({
            enter: $.FroalaEditor.ENTER_BR,
            heightMin: 300,
            imagePaste: true,
            imageDefaultWidth: 0,
            iframe: true,
            toolbarSticky: false,
            key: '{{ froala_key }}',
            toolbarButtons: ['bold','italic','underline','insertLink','html'],
            toolbarButtonsXS:['bold','italic','underline','insertLink','html'],
            toolbarButtonsMD:['bold','italic','underline','insertLink','html'],
            toolbarButtonsSM:['bold','italic','underline','insertLink','html'],
            placeholderText: 'Rules'
        });
        $('#competition_prices').froalaEditor({
            enter: $.FroalaEditor.ENTER_BR,
            heightMin: 300,
            imagePaste: true,
            imageDefaultWidth: 0,
            iframe: true,
            toolbarSticky: false,
            key: '{{ froala_key }}',
            toolbarButtons: ['bold','italic','underline','insertLink','html'],
            toolbarButtonsXS:['bold','italic','underline','insertLink','html'],
            toolbarButtonsMD:['bold','italic','underline','insertLink','html'],
            toolbarButtonsSM:['bold','italic','underline','insertLink','html'],
            placeholderText: 'Prices'
        });
    </script>
{% endblock atm_competition_javascripts %}

Resources/views/Competition/edit.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}

{% block atm_competition_stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/css/jquery-ui.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/css/jquery-ui.theme.min.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/css/froala_editor.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/css/froala_style.css') }}">
    <style>
        .ui-state-default{width: 100% !important;text-align: center !important;}
        .fr-view {font-family:"Quicksand", sans-serif !important;}
    </style>
{% endblock atm_competition_stylesheets %}

{% block atm_competition_content %}
    <form action="{{ path('atm_competition_edit',{ 'competitionId': competition.id }) }}" method="post" id="frmCompetition" enctype="multipart/form-data">
        <h1>Edit Competition: {{ competition.name | title }}</h1>
        <div class="half">
            <fieldset>
                {{ form_widget(form.name) }}
            </fieldset>
            <fieldset>
            {{ form_widget(form.init_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.end_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.register_init_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.register_end_date) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.prices) }}
            </fieldset>
            <fieldset>
                {{ form_widget(form.rules) }}
            </fieldset>
        </div>
        <div class="half">
            <fieldset>
                <img src="{{ asset(competition.image) }}" id="imgPreview">
                <input type="file" name="flImage" id="flImage">
            </fieldset>
        </div>
        <div class="clear"></div>
        <input type="submit" class="but blue" value="Save">
        {{ form_rest(form) }}
    </form>
{% endblock atm_competition_content %}

{% block atm_competition_javascripts %}
    <script src="{{ asset('bundles/atmcompetition/js/jquery-ui.min.1121.js') }}"></script>
    <script src="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/js/froala_editor.min.js') }}"></script>
    <script src="{{ asset('bundles/atmcompetition/plugins/froala_2.1.0/js/plugins/link.min.js') }}"></script>
    <script>
        $( function() {
            var dateFormat = "dd-mm-yy",
                from = $( "#competition_init_date" )
                    .datepicker({
                        dateFormat: dateFormat,
                        defaultDate: "{{ competition.initDate | date('d/m/Y') }}",
                        changeMonth: true,
                        numberOfMonths: 3
                    }).on( "change", function() {
                        to.datepicker( "option", "minDate", getDate( this ) );
                    }),
                to = $( "#competition_end_date" ).datepicker({
                    dateFormat: dateFormat,
                    defaultDate: "{{ competition.endDate | date('d/m/Y') }}",
                    changeMonth: true,
                    numberOfMonths: 3
                }).on( "change", function() {
                    from.datepicker( "option", "maxDate", getDate( this ) );
                });

            function getDate( element ) {
                var date;
                try {
                    date = $.datepicker.parseDate( dateFormat, element.value );
                } catch( error ) {
                    date = null;
                }

                return date;
            }
        } );

        $('#flImage').on('change', function() {
            var currentInput = $(this);
            var file = currentInput[0].files[0];

            var reader = new FileReader();
            reader.onload = function(e){
                $('#imgPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(file);
        });

        $('#competition_rules').froalaEditor({
            enter: $.FroalaEditor.ENTER_BR,
            heightMin: 300,
            imagePaste: true,
            imageDefaultWidth: 0,
            iframe: true,
            toolbarSticky: false,
            key: '{{ froala_key }}',
            toolbarButtons: ['bold','italic','underline','insertLink'],
            toolbarButtonsXS:['bold','italic','underline','insertLink'],
            toolbarButtonsMD:['bold','italic','underline','insertLink'],
            toolbarButtonsSM:['bold','italic','underline','insertLink'],
            placeholderText: 'Rules'
        });
        $('#competition_prices').froalaEditor({
            enter: $.FroalaEditor.ENTER_BR,
            heightMin: 300,
            imagePaste: true,
            imageDefaultWidth: 0,
            iframe: true,
            toolbarSticky: false,
            key: '{{ froala_key }}',
            toolbarButtons: ['bold','italic','underline','insertLink'],
            toolbarButtonsXS:['bold','italic','underline','insertLink'],
            toolbarButtonsMD:['bold','italic','underline','insertLink'],
            toolbarButtonsSM:['bold','italic','underline','insertLink'],
            placeholderText: 'Prices'
        });
    </script>
{% endblock atm_competition_javascripts %}

Resources/views/Competition/list.html.twig
{% extends 'ATMCompetitionBundle:Admin:base.html.twig' %}


{% block atm_competition_content %}
    <h1 class="title">Competitions</h1>
    <div class="competitions">
        {% for competition in competitions %}
            {% include 'ATMCompetitionBundle:Competition:item/competition.html.twig' with { 'competition' : competition } %}
        {% endfor %}
        <div class="clear"></div>
        {% if pagination %}
            <div class="navigation">
                {{ knp_pagination_render(pagination) }}
            </div>
        {% endif %}
        <div class="clear"></div>
    </div>
{% endblock atm_competition_content %}

Resources/views/Competition/votes_results.html.twig
<table>
    <thead>
        <tr>
            <th>Vote date</th>
            <th>Email</th>
            <th>Contestant</th>
        </tr>
    </thead>
    <tbody>
        {% for vote in votes %}
            <tr>
                <td>
                    {{ vote.creationDate | date('d/m/Y') }}
                </td>
                <td>
                    {{ vote.email }}
                </td>
                <td>
                    {{ contestant_name[vote.contestantId] | title }}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% if pagination %}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endif %}
<div class="clear"></div>